version: '2.1'

services:

  redisserver:
    image: redis
    expose:
      - "6379"
    networks:
      - mynet
  
  myapp:
    build:
      context: myapp
    image: myapp:latest
    environment:
      - NOMBRE=Silviu
      - PORT=5000
    ports:
      - "80:5000"
    volumes:
      - ./myapp/app:/app
    depends_on:
      - redisserver
    networks:
      - mynet

networks:
  mynet:
    name: mynet-network 
